//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPrakt.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int id_Role { get; set; }
        public string Title { get; set; }
    
        public virtual User User { get; set; }
    }
}
