//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPrakt.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int id_Student { get; set; }
        public string FIO { get; set; }
        public string Groups { get; set; }
        public int Specialization_id { get; set; }
    
        public virtual Specialization Specialization { get; set; }
    }
}
